### ISSUE TITLE
Shiny

### ISSUE THREAD

**Issue by myneuronews** [jackwasey/PRISMAstatement#1]
Hello,
is it possible to display a prisma flowchart in a shiny app?

thanks

**Comment by jackwasey** [comment]
I don't think it would be complicated. I'd welcome a contribution to do this.

**Comment by myneuronews** [comment]
Finally figured this out using grVizOutput.

Here's an example!!

library(shiny)
library(PRISMAstatement)
library(DiagrammeR)


ui = shinyUI(fluidPage(

  titlePanel("Prismastatement"),

  sidebarLayout(
    sidebarPanel(
     downloadButton('savePlot', 'Download')
    ),
    mainPanel(
      	 grVizOutput("myImage", height=800, width="100%")
    )
  )
))

server = function(input, output) {

  output$myImage <- renderGrViz({
  
  prisma(found = 750,
       found_other = 123,
       no_dupes = 776, 
       screened = 776, 
       screen_exclusions = 13, 
       full_text = 763,
       full_text_exclusions = 17, 
       qualitative = 746, 
       quantitative = 319)


  })
  
	  }
shinyApp(ui = ui, server = server)
